name: Smartsheet Tracking and Reporting

on:
  # TEMPORARY: Hourly tracking for testing (revert after a few days)
  schedule:
    - cron: '0 * * * *'        # Hourly tracking (every hour at :00)
    # - cron: '0 0 * * *'      # Daily tracking (midnight UTC) - DISABLED FOR TESTING
    # - cron: '0 1 * * MON'    # Weekly report (1 AM UTC on Monday) - DISABLED FOR TESTING
    # - cron: '0 2 1 * *'      # Monthly report (2 AM UTC on 1st of month) - DISABLED FOR TEST
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'track'
        type: choice
        options:
          - track
          - weekly-report
          - monthly-report
          - bootstrap
          - reset
          - test-changes

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper git operations

      - name: Pull latest changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git pull --rebase origin main || git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartsheet-python-sdk python-dotenv reportlab

      # Determine which scheduled task to run based on the cron expression that triggered it
      - name: Determine scheduled task
        if: github.event_name == 'schedule'
        id: determine-task
        run: |
          # Use the actual cron expression that triggered this run
          CRON="${{ github.event.schedule }}"
          echo "Triggered by cron: $CRON"
          
          if [[ "$CRON" == "0 0 * * *" ]]; then
            echo "task=track" >> $GITHUB_OUTPUT
          elif [[ "$CRON" == "0 1 * * MON" ]]; then
            echo "task=weekly-report" >> $GITHUB_OUTPUT
          elif [[ "$CRON" == "0 2 1 * *" ]]; then
            echo "task=monthly-report" >> $GITHUB_OUTPUT
          else
            echo "Unknown cron expression: $CRON"
            echo "task=track" >> $GITHUB_OUTPUT  # Default to track
          fi

      - name: Run track
        # CORRECTED: This condition is now robust and won't fail on scheduled runs.
        if: github.event.inputs.action == 'track' || (success() && steps.determine-task.outputs.task == 'track')
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py

      - name: Run weekly report
        # CORRECTED: This condition is now robust.
        if: github.event.inputs.action == 'weekly-report' || (success() && steps.determine-task.outputs.task == 'weekly-report')
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --weekly --previous --force

      - name: Run monthly report
        # CORRECTED: This condition is now robust.
        if: github.event.inputs.action == 'monthly-report' || (success() && steps.determine-task.outputs.task == 'monthly-report')
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_report.py --monthly --previous --force

      - name: Run bootstrap
        if: github.event.inputs.action == 'bootstrap'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --bootstrap

      - name: Reset state
        if: github.event.inputs.action == 'reset'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --reset

      - name: Test changes
        if: github.event.inputs.action == 'test-changes'
        env:
          SMARTSHEET_TOKEN: ${{ secrets.SMARTSHEET_TOKEN }}
        run: |
          python smartsheet_tracker.py --test
          python smartsheet_tracker.py

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: smartsheet-logs
          path: |
            smartsheet_tracker.log
            smartsheet_report.log
          if-no-files-found: warn # Changed to warn to prevent unnecessary warnings

      - name: Commit changes
        if: github.event.inputs.action != '' || steps.determine-task.outputs.task != ''
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          mkdir -p reports/weekly reports/monthly
          git add tracking_data/ reports/
          COMMIT_MSG="${{ github.event.inputs.action || steps.determine-task.outputs.task }} $(date +'%Y-%m-%d')"
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          # Pull latest before pushing to avoid conflicts with concurrent runs
          git pull --rebase origin main || git pull origin main
          git push
